name: Build & Publish Graph

on:
  # Chain after the data workflow completes
  workflow_run:
    workflows: ["Build data-source table"]   # must match the other workflow's `name:`
    types: [completed]
  # Allow manual runs too
  workflow_dispatch:

jobs:
  graph:
    # Run if:
    #  - manual dispatch, OR
    #  - workflow_run that succeeded (and only from main)
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install pyvis networkx jinja2

      - name: Build graph artifacts
        run: |
          python scripts/build_graph.py
          echo "== docs ==" && ls -laR docs || true
          echo "== assets ==" && ls -laR assets || true

      - name: Commit graph (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A docs assets
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "graph: update docs/graph.html (and index.html) & assets/graph.png"
          git push

