name: Load Neo4j (from data/*.csv)
on:
  workflow_dispatch:

jobs:
  load:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Show files
        run: |
          ls -la data || true
          head -n 20 data/datasources.csv || true
          head -n 20 data/lineage.csv || true

      - name: Load into Neo4j
        env:
          NEO4J_URI:  ${{ secrets.NEO4J_URI }}   # e.g., bolt+s://<host>:7687 for Neo4j Aura, or bolt://host:7687
          NEO4J_USER: ${{ secrets.NEO4J_USER }}
          NEO4J_PASS: ${{ secrets.NEO4J_PASS }}
          # Optional overrides if your paths differ:
          # DATASOURCES_PATH: data/datasources.csv
          # LINEAGE_PATH: data/lineage.csv
        run: python scripts/load_neo4j.py
